name: Publish to docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: YOURNAME
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nebular10/publish-packages/game
          
          tag_with_sha: true
